### ISSUE TITLE
bug fixes in 05_NEON-integration-with-field-and-drone-data

### ISSUE THREAD

**Issue by mikoontz** [mikoontz/neon-drone-workflow#2]
Good spotting by @vscholl! To be addressed...

2 more observation as I work through the code:  

[05_NEON-field-data-integration-with-drone/01_create-dtm-and-chm.R](https://github.com/mikoontz/neon-drone-workflow/blob/bc2e191d5a1c804ed2d50221350ae2507da15265/workflow/05_NEON-field-data-integration-with-drone/01_create-dtm-and-chm.R) 

in line 85, local_utm does not appear to be defined earlier in the script:
`dsm <- terra::project(x = dsm, y = paste0("epsg:", local_utm), method = "bilinear")`

local_utm is defined in the[ 06_NEON-AOP-data-integration-with-drone/01_get-neon-aop-data.R](https://github.com/mikoontz/neon-drone-workflow/tree/bc2e191d5a1c804ed2d50221350ae2507da15265/workflow/06_NEON-AOP-data-integration-with-drone) script, but users may not be running that script first if they iterate through the workflow files sequentially. 

`local_utm <- paste0("32", ifelse(stringr::str_detect(string = unique(gcp$utmZone), pattern = "N"), yes = "6", no = "7"), stringr::str_extract(unique(gcp$utmZone), pattern = "[0-9]+") %>% as.numeric()`

[05_NEON-field-data-integration-with-drone/02_detect-trees.R ](https://github.com/mikoontz/neon-drone-workflow/blob/bc2e191d5a1c804ed2d50221350ae2507da15265/workflow/05_NEON-field-data-integration-with-drone/02_detect-trees.R)
When plotting the CHM and detected treetops, for some reason they tree top points would not appear on top of the CHM. I experimented and  found that when I removed the st_transform operation, it plots normally now?!

I don't totally understand why the st_transform would be the issue here. Might be worth holding off making this edit until it can be reproduced. But I'm sharing the modification that worked for me: 

Current code:
```
plot(chm, col = viridis::viridis(100))
plot(ttops %>% st_transform(4326) %>% st_geometry(), add = TRUE, pch = 19, col = "red")  
```

Modified code (for fun, I added the "cex" parameter to set point size)
`plot(ttops %>% st_geometry(), add = TRUE, pch = 19, cex = 0.8, col = "red")`

**Comment by mikoontz** [comment]
Should be working now; thanks @vscholl!

**Comment by vscholl** [comment]
great work! I hope to return to this code again one day soon and re-run the scripts. will report back if i notice any other bugs!
